# app.py (통째로 교체)
import io
import os
import zipfile
from dataclasses import dataclass
from typing import List, Tuple

import streamlit as st
from PIL import Image, ImageOps


# =========================
# Page Config
# =========================
st.set_page_config(
    page_title="MISHARP Image Maker",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# =========================
# Theme / UI CSS
# =========================
CSS = """
<style>
/* 전체 배경 톤 */
.stApp { background: #f7f8fa; }

/* 상단 여백 정리 */
.block-container { padding-top: 1.4rem; padding-bottom: 3rem; }

/* 상단 타이틀 영역 */
.hero {
  max-width: 1600px;
  margin: 0 auto 18px auto;
  padding: 18px 16px;
}
.hero-inner{
  background: linear-gradient(90deg, #0a2a1f, #0a3a2b);
  border-radius: 22px;
  padding: 22px 22px;
  color: #ffffff;
  display:flex;
  justify-content: space-between;
  align-items: center;
  gap: 18px;
  box-shadow: 0 12px 30px rgba(0,0,0,0.10);
}
.hero-title{
  font-size: 22px;
  font-weight: 800;
  letter-spacing: 0.3px;
  margin: 0;
}
.hero-sub{
  margin: 6px 0 0 0;
  opacity: 0.9;
  font-size: 13px;
  line-height: 1.4;
}
.hero-badge{
  background: rgba(255,255,255,0.12);
  border: 1px solid rgba(255,255,255,0.18);
  border-radius: 999px;
  padding: 10px 14px;
  font-size: 12px;
  white-space: nowrap;
}

/* 전체 3단 레이아웃 wrapper */
.page-wrap{
  max-width: 1600px;
  margin: 0 auto;
  padding: 0 16px;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  gap: 40px;
}

/* 좌우 배너 */
.side{
  flex: 0 0 340px;
  position: sticky;
  top: 92px;
}
.side img{
  width: 100%;
  height: auto;
  object-fit: contain; /* ✅ 잘림 방지 핵심 */
  border-radius: 22px;
  display: block;
  box-shadow: 0 10px 26px rgba(0,0,0,0.08);
}

/* 중앙 카드 */
.center{
  flex: 0 0 760px;
  background: #ffffff;
  border-radius: 24px;
  padding: 34px 34px 26px 34px;
  box-shadow: 0 12px 34px rgba(0,0,0,0.06);
  border: 1px solid rgba(0,0,0,0.05);
}

/* 섹션 타이틀 */
.sec-title{
  font-size: 18px;
  font-weight: 800;
  margin: 0 0 6px 0;
}
.sec-cap{
  margin: 0 0 18px 0;
  color: rgba(0,0,0,0.55);
  font-size: 13px;
}

/* 버튼 스타일 (Streamlit 기본 버튼을 더 "부드럽게") */
div.stButton > button{
  border-radius: 14px !important;
  padding: 10px 14px !important;
  font-weight: 700 !important;
}

/* info 박스 라운딩 */
div[data-testid="stAlert"]{
  border-radius: 14px;
}

/* 파일업로더 라운딩 */
section[data-testid="stFileUploaderDropzone"]{
  border-radius: 16px !important;
}

/* 모바일/좁은 화면: 배너 숨김 + 중앙 100% */
@media (max-width: 1200px){
  .side { display: none; }
  .page-wrap{ gap: 0; }
  .center { flex: 1 1 auto; width: 100%; }
  .hero { padding: 18px 12px; }
}

/* 아주 좁은 화면 */
@media (max-width: 520px){
  .center { padding: 22px 18px; border-radius: 18px; }
  .hero-inner{ flex-direction: column; align-items:flex-start; }
  .hero-badge{ width: 100%; text-align:center; }
}
</style>
"""
st.markdown(CSS, unsafe_allow_html=True)


# =========================
# Config
# =========================
MAX_FILES = 10
MAX_FILE_MB = 200

# 좌/우 배너 이미지 (원하는 이미지로 교체)
LEFT_BANNER_URL = "https://via.placeholder.com/420x920.png?text=MISHARP+LEFT+BANNER"
RIGHT_BANNER_URL = "https://via.placeholder.com/420x920.png?text=MISHARP+RIGHT+BANNER"


# =========================
# Helpers
# =========================
@dataclass
class OutputFile:
    path_in_zip: str
    data: bytes


def safe_open_image(file) -> Image.Image:
    """업로드 파일을 PIL 이미지로 안전하게 오픈"""
    img = Image.open(file)
    img = ImageOps.exif_transpose(img)  # EXIF 회전 보정
    if img.mode not in ("RGB", "RGBA"):
        img = img.convert("RGB")
    return img


def jpeg_bytes(img: Image.Image, quality: int = 85) -> bytes:
    """PIL Image -> JPG bytes"""
    if img.mode == "RGBA":
        # 투명 배경은 흰색 합성
        bg = Image.new("RGB", img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[-1])
        img = bg
    elif img.mode != "RGB":
        img = img.convert("RGB")

    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=int(quality), optimize=True)
    return buf.getvalue()


def build_outputs(uploaded_files, quality: int) -> Tuple[List[OutputFile], List[str]]:
    """
    ✅ 여기 함수가 '생성 로직' 본체입니다.
    현재는: 업로드 이미지를 JPG로 변환 + zip 구성 (샘플)
    형준님 상세페이지 생성 로직이 있다면, 이 함수 안쪽만 교체해 붙이면 됩니다.
    """
    outputs: List[OutputFile] = []
    logs: List[str] = []

    for f in uploaded_files:
        try:
            img = safe_open_image(f)
            jpg = jpeg_bytes(img, quality=quality)

            base = os.path.splitext(f.name)[0]
            out_name = f"{base}.jpg"
            outputs.append(OutputFile(path_in_zip=f"output/{out_name}", data=jpg))
            logs.append(f"✅ {f.name} → {out_name} (quality={quality})")
        except Exception as e:
            logs.append(f"❌ {f.name} 처리 실패: {e}")

    # 예: 추가 산출물(설명 txt)도 zip에 같이 넣기
    note = (
        "MISHARP Image Maker\n"
        f"- Files: {len(uploaded_files)}\n"
        f"- Quality: {quality}\n"
        "Generated by app.py template.\n"
    ).encode("utf-8")
    outputs.append(OutputFile(path_in_zip="README.txt", data=note))

    return outputs, logs


def make_zip_bytes(files: List[OutputFile]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for item in files:
            z.writestr(item.path_in_zip, item.data)
    return buf.getvalue()


def reset_app():
    for k in list(st.session_state.keys()):
        if k.startswith("misharp_"):
            del st.session_state[k]


# =========================
# State
# =========================
if "misharp_last_zip" not in st.session_state:
    st.session_state["misharp_last_zip"] = None
if "misharp_logs" not in st.session_state:
    st.session_state["misharp_logs"] = []
if "misharp_done" not in st.session_state:
    st.session_state["misharp_done"] = False


# =========================
# Header (Hero)
# =========================
st.markdown(
    """
<div class="hero">
  <div class="hero-inner">
    <div>
      <p class="hero-title">MISHARP 상세페이지 이미지 생성기</p>
      <p class="hero-sub">
        JPG/PNG 업로드 → 생성 → ZIP 다운로드까지 한 번에.<br>
        양쪽 배너는 <b>잘림 없이</b> 보이도록 레이아웃을 안정적으로 구성했습니다.
      </p>
    </div>
    <div class="hero-badge">2006부터 지금까지, 미샵의 작업툴</div>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

# =========================
# Layout (Left / Center / Right)
# =========================
st.markdown('<div class="page-wrap">', unsafe_allow_html=True)

# Left banner
st.markdown('<div class="side">', unsafe_allow_html=True)
st.image(LEFT_BANNER_URL, use_container_width=True)
st.markdown("</div>", unsafe_allow_html=True)

# Center card
st.markdown('<div class="center">', unsafe_allow_html=True)

st.markdown('<div class="sec-title">파일선택</div>', unsafe_allow_html=True)
st.markdown(
    f'<div class="sec-cap">JPG/PNG 파일을 업로드하세요. 최대 {MAX_FILES}개까지 가능합니다.</div>',
    unsafe_allow_html=True,
)

uploaded = st.file_uploader(
    " ",
    type=["jpg", "jpeg", "png"],
    accept_multiple_files=True,
    key="misharp_uploader",
)

# 업로드 제한 처리
if uploaded and len(uploaded) > MAX_FILES:
    st.warning(f"최대 {MAX_FILES}개까지 업로드 가능합니다. 현재 {len(uploaded)}개입니다.")
    uploaded = uploaded[:MAX_FILES]

quality = st.slider(
    "이미지 품질 (0~100)",
    0,
    100,
    50,
    key="misharp_quality",
)

btn_col1, btn_col2 = st.columns([1, 1], gap="large")
with btn_col1:
    gen = st.button("생성하기 (JPG)", use_container_width=True, key="misharp_generate")
with btn_col2:
    rst = st.button("초기화", use_container_width=True, key="misharp_reset")

if rst:
    reset_app()
    st.rerun()

st.markdown("### 업로드 파일명")
if uploaded:
    for f in uploaded:
        st.write(f"- {f.name}")
else:
    st.info("아직 업로드된 파일이 없습니다.")

# Generate
if gen:
    if not uploaded:
        st.warning("먼저 파일을 업로드해 주세요.")
    else:
        with st.spinner("생성 중입니다..."):
            out_files, logs = build_outputs(uploaded, quality=quality)
            zip_bytes = make_zip_bytes(out_files)
            st.session_state["misharp_last_zip"] = zip_bytes
            st.session_state["misharp_logs"] = logs
            st.session_state["misharp_done"] = True

# Result
if st.session_state.get("misharp_done") and st.session_state.get("misharp_last_zip"):
    st.success("생성이 완료되었습니다. 아래에서 ZIP 파일을 다운로드하세요.")
    st.download_button(
        label="ZIP 다운로드",
        data=st.session_state["misharp_last_zip"],
        file_name="misharp_outputs.zip",
        mime="application/zip",
        use_container_width=True,
        key="misharp_download",
    )

    with st.expander("처리 로그 보기"):
        for line in st.session_state.get("misharp_logs", []):
            st.write(line)

st.markdown("---")
st.caption(
    "※ 이 템플릿은 ‘배너 잘림 문제’가 없도록 레이아웃을 안정화한 app.py입니다. "
    "형준님 기존 상세페이지 생성 로직은 build_outputs() 함수 안쪽만 교체해 연결하시면 됩니다."
)

st.markdown("</div>", unsafe_allow_html=True)  # center end

# Right banner
st.markdown('<div class="side">', unsafe_allow_html=True)
st.image(RIGHT_BANNER_URL, use_container_width=True)
st.markdown("</div>", unsafe_allow_html=True)

st.markdown("</div>", unsafe_allow_html=True)  # page-wrap end
